import { create } from 'zustand'

export interface Slide {
  title: string;
  bullets: string[];
  speakerNotes: string;
  backgroundColor: string;
  textColor: string;
  audioUrl?: string;
  duration?: number;
}

export interface EnhancedSlide extends Slide {
  layoutType: 'title' | 'content' | 'quote' | 'statistics' | 'timeline' | 'image' | 'comparison' | 'conclusion';
  gradient?: string;
  accentColor?: string;
  subtitle?: string;
  description?: string;
  imageUrl?: string;
  icon?: string;
  htmlContent?: string; // HTML/CSS code generated by Gemini
}

interface SlidesState {
  topic: string;
  style: string;
  slideCount: number;
  slides: EnhancedSlide[];
  isGenerating: boolean;
  hasSubmitted: boolean;

  setTopic: (topic: string) => void;
  setStyle: (style: string) => void;
  setSlideCount: (count: number) => void;
  setSlides: (slides: EnhancedSlide[]) => void;
  setIsGenerating: (isGenerating: boolean) => void;
  setHasSubmitted: (hasSubmitted: boolean) => void;
  updateSlide: (index: number, updates: Partial<EnhancedSlide>) => void;
  reset: () => void;
}

export const useSlidesStore = create<SlidesState>((set) => ({
  topic: '',
  style: 'Modern',
  slideCount: 5,
  slides: [],
  isGenerating: false,
  hasSubmitted: false,

  setTopic: (topic) => set({ topic }),
  setStyle: (style) => set({ style }),
  setSlideCount: (slideCount) => set({ slideCount }),
  setSlides: (slides) => set({ slides }),
  setIsGenerating: (isGenerating) => set({ isGenerating }),
  setHasSubmitted: (hasSubmitted) => set({ hasSubmitted }),
  updateSlide: (index, updates) => set((state) => {
    const newSlides = [...state.slides];
    newSlides[index] = { ...newSlides[index], ...updates };
    return { slides: newSlides };
  }),
  reset: () => set({
    topic: '',
    slides: [],
    isGenerating: false,
    hasSubmitted: false,
  }),
}))
